# Generated by Django 6.0 on 2026-04-23 16:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount in the local currency', max_digits=12)),
                ('category', models.CharField(choices=[('food', 'Food'), ('transport', 'Transport'), ('utilities', 'Utilities'), ('entertainment', 'Entertainment'), ('shopping', 'Shopping'), ('healthcare', 'Healthcare'), ('other', 'Other')], default='other', max_length=50)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('idempotency_key', models.CharField(db_index=True, help_text='Used to prevent duplicate expense entries from retried requests', max_length=255, unique=True)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['category', '-date'], name='expenses_ex_categor_c028e2_idx'), models.Index(fields=['-created_at'], name='expenses_ex_created_be0371_idx')],
            },
        ),
    ]
